---
title: "Week 1: "
subtitle: "Introduction to EDS 241 - Conceptual Overview of Regression & Causal Inference Concepts"
description: "Wednesday January 8^th^, 2025"
---

::: {.callout-tip}
# Welcome to the page for all things Week 1!
:::

## {{< fa person-chalkboard title="a person pointing at a chalkboard" >}} Lecture Materials {#lecture-materials}

| Lecture slides | Lab |  Answer key |
|----------------|------|------------|
| [Lecture 1: Intro. to Casual Inference](https://drive.google.com/file/d/1FzwRi8Lh6snUfv5gX4fa-APQxk9TnVVz/view?usp=sharing){target="_blank"} | [Handout: Lab 1](https://garberadamc.github.io/project-site/Lab1-Generalize-Fast){target="_blank"} , [Repository: Lab 1](https://github.com/garberadamc/Lab1-EDS241-Buntaine24){target="_blank"} | |

: {.hover .bordered tbl-colwidths="[50,25,25]"} 


## {{< fa pencil title="pencil" >}} Assignment Reminders {#assignment-reminders}

| Assignment Type | Assignment Title                              | Date Assigned  | Date Due                   |
|-----------------|-----------------------------------------------|----------------|----------------------------|
| End of Class Survey | [EOC-Week1](https://forms.gle/e1SFjjG4xsgMx88s7){target="_blank"} | 01/08/2025 | 01/08/2025, 11:55pm |
| Assignment 1 | [Handout: HW1-LOBSTRS](https://garberadamc.github.io/project-site/hw1-lobstrs-eds241){target="_blank"} , [Repository: HW1-LOBSTRS](https://github.com/garberadamc/HW1-LOBSTRS-EDS241.git){target="_blank"} | 01/08/2025 | 01/26/2025, 11:59pm |
| Reading - *Mastering 'Metrics*  | A&P: Chapter 2  | 01/08/2025 | 01/15/2025 |
| Reading - Article  | Careful read: [Buntaine et al. (2024)](https://drive.google.com/file/d/1bvW40xguud2Y_bRnxwjCCZSmAZALgQTn/view){target="_blank"}  | 01/08/2025 | (1) Read study carefully before the guest lecture! (2) Think of questions for Prof. Mark Buntaine |

: {.hover .bordered tbl-colwidths="[20,30,20,30]"} 

<br>

::: {.callout-tip}
# Assignment Submission and Rubric

- **Submission:** Submit assignments through `GradeScope`
- **Question-specific guide:** Each question has detailed grading criteria available on `GradeScope`. Be sure to review these guidelines before submitting your work!
- **General rubric outline:** For an overview of the grading criteria, refer to the [assignment rubric - general outline](https://docs.google.com/document/d/1JovgsTOiPCeUy5eehs9a4nPx5VoLlILV-1m_LBarmQU/edit?usp=sharing)
:::

## {{< fa comments title="two speech bubbles" >}} Extra Resources {#discussion-materials}

<br>

::: {.left-text}
[**References**]{.teal-text .body-text-m}

- [Gelman, A., & Loken, E. (2013) ](https://drive.google.com/file/d/1Cx2fqgKDTzMQjXtyo4Cz2YK4dQQzpb4Z/view?usp=drive_link){target="_blank"}. *The garden of forking paths: Why multiple comparisons can be a problem, even when there is no “fishing expedition” or “p-hacking” and the research hypothesis was posited ahead of time.* Department of Statistics, Columbia University, 348(1-17), 3.
- [Buntaine, M. T., Komakech, P., & Shen, S. V. (2024)](https://drive.google.com/file/d/1bvW40xguud2Y_bRnxwjCCZSmAZALgQTn/view?usp=sharing). *Social competition drives collective action to reduce informal waste burning in Uganda.* Proceedings of the National Academy of Sciences, 121(23), e2319712121.


:::